version: '3.8'

services:
  frontend:
    build:
      context: ./devLinks_React
      dockerfile: Dockerfile
    ports:
      - "5173:5173"


  backend:
    build:
      context: ./FileUpload
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
